# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('userinfo', '0002_auto_20190725_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_stock', models.IntegerField(verbose_name='持有数量')),
                ('frozen_stock', models.IntegerField(verbose_name='冻结')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='金额')),
                ('pay_pwd', models.CharField(max_length=200, null=True, verbose_name='支付密码')),
                ('frozen_money', models.CharField(max_length=200, null=True, verbose_name='冻结资金')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '钱包表',
                'verbose_name_plural': '钱包表',
            },
        ),
    ]
