# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=50, null=True, verbose_name='广告名称')),
                ('ad_url', models.URLField(verbose_name='链接')),
                ('ad_img', models.ImageField(default='normal.png', upload_to='img/ad', verbose_name='图片')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sto_No', models.CharField(max_length=20, null=True, verbose_name='股票代码')),
                ('sto_name', models.CharField(max_length=50, null=True, verbose_name='股票名称')),
                ('sto_company', models.CharField(max_length=200, null=True, verbose_name='股票公司')),
                ('sto_area', models.IntegerField(choices=[(0, '金融'), (1, 'IT'), (2, '体育'), (3, '医药'), (4, '教育'), (5, '餐饮'), (6, '娱乐'), (7, '影视'), (8, '房地产')], default=0, verbose_name='股票领域')),
                ('sto_update', models.DateField(verbose_name='上市时间')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
            },
        ),
    ]
