# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-16 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20190716_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=9999, max_digits=7, verbose_name='零售价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub',
            field=models.CharField(max_length=50, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='书名'),
        ),
    ]
