# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190716_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Author')),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'boook', 'verbose_name_plural': 'booksss'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
